# Generated by Django 5.2.1 on 2025-05-28 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                ("latitude", models.FloatField(verbose_name="Широта")),
                ("longitude", models.FloatField(verbose_name="Долгота")),
            ],
        ),
        migrations.CreateModel(
            name="WeatherSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Ключ сессии"
                    ),
                ),
                (
                    "search_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата поиска"),
                ),
                (
                    "weather_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Данные о погоде"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="weather.city"
                    ),
                ),
            ],
        ),
    ]
